title = "Pixelnest Studio"
baseurl = "http://pixelnest.io/"

languageCode = "en-us"
copyright = "© 2016 Pixelnest Studio—we craft games and apps."

publishDir = "_site"

buildDrafts = false

# -------------------------------------------------------
# Globals.
# -------------------------------------------------------

[permalinks]
  post = "/:year/:month/:filename/"

# -------------------------------------------------------
# Pagination.
# -------------------------------------------------------

paginatePath = "journal/:num"
paginate = 4
