#!/usr/bin/env bash

# If it doesn't work the first time, it means that you have a freshly created repo.
# The presskit uses the build branch for its published version. We need to be on that branch in `presskit/`.
# Do that:
#
#   cd presskit/ # This is not a folder, but a reference to a remote commit.
#   git submodule update --remote
#   git checkout build

# Update.
cd presskit/
git checkout build
git pull --rebase=preserve

# Commit.
cd ..
git add presskit/
git commit --message "Update presskit"
